# Generated by Django 3.2.7 on 2021-09-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('card', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=50)),
                ('pay', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='JorgoCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=15)),
                ('numbers', models.IntegerField()),
                ('size', models.CharField(max_length=10)),
                ('timestamp', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='NambaCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=15)),
                ('numbers', models.IntegerField()),
                ('size', models.CharField(max_length=10)),
                ('timestamp', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.CharField(max_length=50)),
                ('drop', models.CharField(max_length=50)),
                ('when', models.CharField(max_length=70)),
                ('price', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YandexCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=15)),
                ('numbers', models.IntegerField()),
                ('size', models.CharField(max_length=10)),
                ('tip', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
