# Generated by Django 3.2.7 on 2021-10-01 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxis_vyzov', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JorgoCar',
        ),
        migrations.DeleteModel(
            name='NambaCar',
        ),
    ]
