# Generated by Django 3.2.7 on 2021-10-01 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxis_vyzov', '0002_auto_20211001_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='drop',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='pickup',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='when',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='time',
        ),
    ]
