# Generated by Django 3.2.7 on 2021-10-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis_vyzov', '0005_auto_20211002_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
